// Banco de alimentos comuns (valores por 100g) — fonte: médias de tabelas nutricionais (TACO/USDA), aproximadas.
// kcal, proteina (p), carboidrato (c), gordura (g) em gramas por 100g do alimento.
// group: categoria do alimento pro plano de refeições (carbo, leguminosa, proteina, vegetal, fruta, laticinio, gordura, suplemento).
const FOOD_DB = [
  { name: "Arroz branco cozido", kcal: 128, p: 2.5, c: 28, g: 0.2, group: "carbo" },
  { name: "Arroz integral cozido", kcal: 124, p: 2.6, c: 25.8, g: 1.0, group: "carbo" },
  { name: "Feijão carioca cozido", kcal: 76, p: 4.8, c: 13.6, g: 0.5, group: "leguminosa" },
  { name: "Feijão preto cozido", kcal: 77, p: 4.5, c: 14, g: 0.5, group: "leguminosa" },
  { name: "Peito de frango grelhado", kcal: 159, p: 32, c: 0, g: 3.6, group: "proteina" },
  { name: "Frango desfiado (cozido)", kcal: 165, p: 31, c: 0, g: 3.6, group: "proteina" },
  { name: "Carne bovina moída (magra, cozida)", kcal: 172, p: 26, c: 0, g: 7, group: "proteina" },
  { name: "Patinho grelhado", kcal: 163, p: 30, c: 0, g: 4.2, group: "proteina" },
  { name: "Carne suína (lombo, grelhado)", kcal: 187, p: 28, c: 0, g: 8, group: "proteina" },
  { name: "Ovo", kcal: 155, p: 13, c: 1.1, g: 11, group: "proteina" },
  { name: "Clara de ovo", kcal: 52, p: 11, c: 0.7, g: 0.2, group: "proteina" },
  { name: "Tilápia grelhada", kcal: 128, p: 26, c: 0, g: 2.7, group: "proteina" },
  { name: "Salmão grelhado", kcal: 208, p: 22, c: 0, g: 13, group: "proteina" },
  { name: "Atum em água (lata)", kcal: 116, p: 26, c: 0, g: 1, group: "proteina" },
  { name: "Batata doce cozida", kcal: 86, p: 1.6, c: 20, g: 0.1, group: "carbo" },
  { name: "Batata inglesa cozida", kcal: 87, p: 1.9, c: 20, g: 0.1, group: "carbo" },
  { name: "Mandioca cozida", kcal: 125, p: 0.6, c: 30, g: 0.3, group: "carbo" },
  { name: "Macarrão cozido", kcal: 131, p: 5, c: 25, g: 1.1, group: "carbo" },
  { name: "Pão francês", kcal: 300, p: 9, c: 58, g: 3, group: "carbo" },
  { name: "Pão integral", kcal: 260, p: 10, c: 48, g: 3.2, group: "carbo" },
  { name: "Aveia em flocos", kcal: 389, p: 17, c: 66, g: 7, group: "carbo" },
  { name: "Tapioca (goma hidratada)", kcal: 104, p: 0.1, c: 25.7, g: 0, group: "carbo" },
  { name: "Banana", kcal: 89, p: 1.1, c: 23, g: 0.3, group: "fruta" },
  { name: "Maçã", kcal: 52, p: 0.3, c: 14, g: 0.2, group: "fruta" },
  { name: "Abacate", kcal: 160, p: 2, c: 8.5, g: 15, group: "fruta" },
  { name: "Laranja", kcal: 47, p: 0.9, c: 12, g: 0.1, group: "fruta" },
  { name: "Mamão", kcal: 43, p: 0.5, c: 11, g: 0.1, group: "fruta" },
  { name: "Morango", kcal: 32, p: 0.7, c: 7.7, g: 0.3, group: "fruta" },
  { name: "Alface", kcal: 15, p: 1.4, c: 2.9, g: 0.2, group: "vegetal" },
  { name: "Tomate", kcal: 18, p: 0.9, c: 3.9, g: 0.2, group: "vegetal" },
  { name: "Brócolis cozido", kcal: 35, p: 2.4, c: 7, g: 0.4, group: "vegetal" },
  { name: "Cenoura crua", kcal: 41, p: 0.9, c: 10, g: 0.2, group: "vegetal" },
  { name: "Salada mista (folhas/legumes crus)", kcal: 22, p: 1.3, c: 4, g: 0.2, group: "vegetal" },
  { name: "Leite integral", kcal: 61, p: 3.2, c: 4.8, g: 3.3, group: "laticinio" },
  { name: "Leite desnatado", kcal: 35, p: 3.4, c: 5, g: 0.1, group: "laticinio" },
  { name: "Iogurte natural integral", kcal: 61, p: 3.5, c: 4.7, g: 3.3, group: "laticinio" },
  { name: "Iogurte natural desnatado", kcal: 41, p: 4.4, c: 5.9, g: 0.2, group: "laticinio" },
  { name: "Queijo minas frescal", kcal: 264, p: 17, c: 3, g: 20, group: "laticinio" },
  { name: "Queijo muçarela", kcal: 280, p: 22, c: 3, g: 20, group: "laticinio" },
  { name: "Requeijão", kcal: 257, p: 9, c: 3, g: 23, group: "laticinio" },
  { name: "Whey protein (pó)", kcal: 400, p: 80, c: 8, g: 6, group: "suplemento" },
  { name: "Hipercalórico (pó)", kcal: 390, p: 14, c: 72, g: 5, group: "suplemento" },
  { name: "Creatina (pó)", kcal: 0, p: 0, c: 0, g: 0, group: "suplemento" },
  { name: "Amendoim torrado", kcal: 567, p: 26, c: 16, g: 49, group: "gordura" },
  { name: "Pasta de amendoim", kcal: 588, p: 25, c: 20, g: 50, group: "gordura" },
  { name: "Castanha do pará", kcal: 656, p: 14, c: 12, g: 66, group: "gordura" },
  { name: "Amêndoas", kcal: 579, p: 21, c: 22, g: 50, group: "gordura" },
  { name: "Azeite de oliva", kcal: 884, p: 0, c: 0, g: 100, group: "gordura" },
  { name: "Óleo de coco", kcal: 862, p: 0, c: 0, g: 100, group: "gordura" },
  { name: "Chocolate amargo 70%", kcal: 546, p: 7.8, c: 46, g: 38, group: "gordura" },
  { name: "Granola", kcal: 471, p: 10, c: 64, g: 20, group: "carbo" },
  { name: "Barra de proteína (média)", kcal: 370, p: 30, c: 35, g: 12, group: "proteina" },
  { name: "Quinoa cozida", kcal: 120, p: 4.4, c: 21, g: 1.9, group: "carbo" },
  { name: "Grão de bico cozido", kcal: 164, p: 8.9, c: 27, g: 2.6, group: "leguminosa" },
  { name: "Lentilha cozida", kcal: 116, p: 9, c: 20, g: 0.4, group: "leguminosa" },
];

// Nomes normalizados para busca (sem acento, minúsculo) — gerado em runtime no app.js
